### ISSUE TITLE
Space between menu icon and opened tabs

### ISSUE THREAD

**Issue by chauhankiran** [BodhiDev/Moksha-dev#1]
I am not sure if this is the place of creating an issue of Moksha desktop environment. If this is not, then please guide me on the where to write the issue.

If I open more than five program in my laptop, it put a open tab upto space between menu icon and first opened tab - https://prnt.sc/jnfli9

**Comment by rbtylee** [comment]
This is not really the place to report this so I will move it to the Moksha repo:

https://github.com/JeffHoogland/moksha/issues/82
